### ISSUE TITLE
How to install RLangSyntax

### ISSUE THREAD

**Issue by dariober** [jacoby/RLangSyntax#1]
Hello- I wanted to have syntax highlighting for R in Komodo (Komodo Edit, version 8.5.4, build 14424, platform linux-x86_64, to be precise). I came across RLangSyntax but... How do I install it/make it work? Apologies, it must be documented somewhere but couldn't find the relevant info.

Many thanks!
Dario

**Comment by jacoby** [comment]
I hadn't noticed this previously. I am so sorry.

I am working on getting it work with 9.0.0, and in the process of getting that going, I was reminded how problematic this is.

I have the build steps added to README, but if you just want the xpi, here it is. 

https://www.dropbox.com/s/lw53t7dqh9agv92/rlangsyntax-0.1.1-ko.xpi?dl=0

**Comment by jacoby** [comment]
Today I learned you can have releases and not just code on GitHub. 

https://github.com/jacoby/RLangSyntax/releases

Enjoy, dariober
