### ISSUE TITLE
Installed the xpi, now what?

### ISSUE THREAD

**Issue by openpencil** [jacoby/RLangSyntax#8]
Dear Jacoby,

Thanks for trying to make the R syntax available for Komodo users. I just installed your current .xpi through the `Tools > Add ons > Install Add-on From File` route and restarted Komodo IDE. On loading up an R file, I don't see any syntax highlighting. Where am I going wrong? Any clues would be super helpful. Thanks so much!
-j

**Comment by jacoby** [comment]
View > View As Language > R

Or

View > View As Language > Other > R

You may have to set this in Edit > Preferences > File Associations to make it permanent.

**Comment by openpencil** [comment]
Thanks so much! It works now.

**Comment by openpencil** [comment]
So it seems like making it permanent only works on a file by file basis. When I open new files I have to go through these steps again. Isn't there some way to make Komodo IDE recognize the file extension and display syntax highlighting automatically? The file-associations panel doesn't seem to have a way to specify this: 
![file associations in komodo IDE](http://i.imgur.com/lgoIcDi.png)

**Comment by jacoby** [comment]
In my experience, trying to add multiple file associations at once doesn't work, and that you should try separate entries for *.R, *.rs and *.Rscript.

It _is_ case-insensitive, I think, so separate *.r and *.R should not be necessary.

This might be a better question for [the Komodo Project itself](https://github.com/komodo), though.
